name: git-invaders

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SVG
        uses: VARDHAMANPATEL23/git-invader@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: ${{ github.repository_owner }}
          color: green
          ship: rocket

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
